### ISSUE TITLE
Model Composition: Add outline for interface element API

### ISSUE THREAD

**Issue by azeey** [osrf/sdf_tutorials#12]
This is to allow libsdformat parse from other formats without having to convert to SDFormat via user provided hooks.

PR: https://github.com/osrf/sdf_tutorials/pull/3 

Potential usage example: https://github.com/RobotLocomotion/drake/pull/13128

**Comment by EricCousineau-TRI** [comment]
Towards https://github.com/osrf/sdformat/issues/278

**Comment by EricCousineau-TRI** [comment]
Oops, forgot to link to this issue from my PR.

Resolved via #3.
