### ISSUE TITLE
Add an SDFormat 1.7 version of the model kinematics tutorial

### ISSUE THREAD

**Issue by scpeters** [osrf/sdf_tutorials#20]
Model kinematics have changed quite a bit from a user perspective in SDFormat 1.7, so we should add an SDFormat 1.7 version of the [model kinematics tutorial](http://sdformat.org/tutorials?tut=spec_model_kinematics&cat=specification&) that describes the new way that model kinematics can be defined with `//frame`, `//pose/@relative_to`, and `//joint/axis/@expressed_in`. It should be at a beginner level and oriented to people creating models, rather than the advanced level aimed at software developers intending to parse SDFormat files that was used in the [pose frame semantics proposal](http://sdformat.org/tutorials?tut=pose_frame_semantics_proposal). Some of the content could be drawn from the [2019 ROSCon presentation](https://roscon.ros.org/2019/talks/roscon2019_poseframespecificationforsdformat1_7.pdf), since I think that was oriented towards people writing models in SDFormat.

**Comment by chapulina** [comment]
@mohamedsayed18 is looking into adding a tutorial as part of the Ignition Knowledge Base which covers beginner usage of SDF 1.7's new features. We think we can find a way to keep the tutorial here and link to it from the Ignition docs entrypoint. Related to https://github.com/ignitionrobotics/docs/issues/23 CC @maryaB-osr

**Comment by chapulina** [comment]
@mohamedsayed18 started a draft in https://github.com/ignitionrobotics/docs/pull/31
